//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support.Datasources.MsCrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactExtensionBase
    {
        public System.Guid ContactId { get; set; }
        public string New_skype { get; set; }
        public string New_site_fullname { get; set; }
        public Nullable<int> New_site_id { get; set; }
        public Nullable<bool> New_Interes { get; set; }
        public Nullable<bool> New_problem { get; set; }
        public Nullable<bool> New_reshenie { get; set; }
        public Nullable<bool> New_neutral { get; set; }
        public Nullable<int> MSA_eServicesAccessLevel { get; set; }
        public Nullable<bool> MSA_webuser { get; set; }
        public Nullable<int> sm_solutation { get; set; }
        public Nullable<System.Guid> new_sotrudniki { get; set; }
        public Nullable<int> svk_role_dlya_podderzhki { get; set; }
        public Nullable<bool> Adx_changepasswordatnextlogon { get; set; }
        public string Adx_CreatedByIPAddress { get; set; }
        public string Adx_CreatedByUsername { get; set; }
        public Nullable<int> Adx_failedpasswordanswerattempts { get; set; }
        public Nullable<System.DateTime> Adx_failedpasswordanswerattemptwindowstart { get; set; }
        public Nullable<int> Adx_failedpasswordattempts { get; set; }
        public Nullable<System.DateTime> Adx_failedpasswordattemptwindowstart { get; set; }
        public string adx_identityprovidername { get; set; }
        public string Adx_InvitationCode { get; set; }
        public Nullable<System.DateTime> Adx_InvitationCodeExpiryDate { get; set; }
        public Nullable<System.DateTime> Adx_lastactivity { get; set; }
        public Nullable<System.DateTime> Adx_lastlockedout { get; set; }
        public Nullable<System.DateTime> Adx_lastpasswordchange { get; set; }
        public Nullable<System.DateTime> Adx_LastSuccessfulLogon { get; set; }
        public Nullable<bool> Adx_lockedout { get; set; }
        public Nullable<bool> Adx_LogonEnabled { get; set; }
        public string Adx_ModifiedByIPAddress { get; set; }
        public string Adx_ModifiedByUsername { get; set; }
        public string Adx_OrganizationName { get; set; }
        public string Adx_password { get; set; }
        public string Adx_passwordanswer { get; set; }
        public string Adx_passwordformat { get; set; }
        public string Adx_passwordquestion { get; set; }
        public string Adx_passwordsalt { get; set; }
        public string Adx_resetpassword { get; set; }
        public Nullable<int> Adx_TimeZone { get; set; }
        public string Adx_username { get; set; }
        public Nullable<System.Guid> adx_systemuserid { get; set; }
        public Nullable<System.Guid> msa_managingpartnerid { get; set; }
        public Nullable<System.Guid> svk_project { get; set; }
        public Nullable<int> iok_web_case_access_level { get; set; }
        public string svk_googlename { get; set; }
        public string iok_vkusername { get; set; }
        public string iok_yandexusername { get; set; }
        public string iok_mailruusername { get; set; }
        public Nullable<int> iok_contact_source { get; set; }
        public string iok_systtechusername { get; set; }
        public string iok_RouteNumber { get; set; }
        public Nullable<bool> iok_telephoneban { get; set; }
        public string new_route { get; set; }
        public Nullable<System.Guid> new_competitorContactFieldSearch { get; set; }
        public string new_mob_tel2 { get; set; }
        public Nullable<int> new_ReaderEntityContact { get; set; }
        public Nullable<int> new_doNotSendMMEntityContact { get; set; }
    
        public virtual ContactBase ContactBase { get; set; }
    }
}
